  name: Bug Report
  description: Report a bug in Minima.
  labels: ["bug"]
  title: "[BUG] "
  body:
    - type: checkboxes
      id: checks
      attributes: 
        label: Have you checked if their is an existing issue for this?
        description: Please check if issue exists
        options:
        - label: I have searched the existing issues
          required: true
      validations:
        required: true
    - type: textarea
      id: description
      attributes:
        label: Description
        description: Please provide a clear and concise description of the bug you encountered.
      validations:
        required: true
      validations:
        required: true
    - type: textarea
      id: reproduce
      attributes:
        label: How to Reproduce
        description: Please outline the steps you followed that led to the bug.
      validations:
        required: true
    - type: textarea
      id: expected
      attributes:
        label: Expected Behavior
        description: What were you expecting to happen when you performed these steps?
      validations:
        required: true
    - type: textarea
      id: actual
      attributes:
        label: Actual Behavior
        description: What actually happened?
      validations:
        required: true
    - type: dropdown
      id: frequency
      attributes:
        label: frequency
        description: How often does this occur?
        multiple: true
        options:
          - Occasionally
          - Always
      validations:
        required: true
    - type: textarea
      id: logs
      attributes:
        label: Relevant Output or Stack Trace
        description: Please share any relevant log output regarding the bug.
        render: Shell
      validations:
        required: false
        ---
    - type: textarea
      id: context
      attributes:
        label: Additional Context
        description: Add any additional context about the problem here.
      validations:
        required: false
    - type: markdown
      attributes:
        value: |
          ## Thanks for reporting this issue! We will get back to you as soon as possible.
