name: testing lint, test and deploy
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "checkout code"
  install:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "checkout code"
      - name: "install dependency"
        run: npm ci
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "checkout code"
      - name: "install dependency"
        run: npm ci
      - name: "echoing"
        run: echo "Starting the linting process"
      - name: "lets start linting"
        run: npm run lint
      - run: echo "Linting process is now completed"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "checkout code"
      - name: "install dependency"
        run: npm ci
      - name: "echoing"
        run: echo "Starting the testing process"
      - name: "lets start testing"
        run: npm run test
      - run: echo "ending the testing process"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "checkout code"
      - name: "install dependency"
        run: npm ci
      - name: "echoing"
        run: echo "Starting the build process" |
             npm run build
      